### PR TITLE
Implement toString() fn in PutMessageAdapter and AckMessageAdapter

### PR DESCRIPTION
**Pull request by sindhunaydu**
*Issue number of the reported bug or feature request: #14*

**Describe your changes**
Implemented toString() in PutMessageAdapter and AckMessageAdapter class.

### CODE REVIEW

**Review by 678098 — COMMENTED** [review]
Looks good, but need to add "Signed-off-by" comment
https://github.com/bloomberg/.github/blob/master/CONTRIBUTING.md#contribution-licensing

You can do this on this 1 commit with `git commit -s --amend` and `git push -f ...`

**Comment by sindhunaydu** [comment]
@678098 thanks for the review. Added "Signed-off-by" comment.

**Comment by sindhunaydu** [comment]
@678098 I noticed that the GH action failed because I used my real name instead of pseudonym. Will update the sign-off comment.

**Comment by 678098** [comment]
@sindhunaydu something like this might help
```
git reset --soft HEAD~3
git commit -s -m "Implement toString() fn in PutMessageAdapter and AckMessageAdapter"
git push -f origin <branch>
```

**Comment by sindhunaydu** [comment]
@678098 thanks, I think I got it right this time.

**Comment by sindhunaydu** [comment]
@678098 I'm so sorry I donno why it failed again. I can see that my signature is correct, but not sure why the check failed. 
Screenshot 2023-08-24 at 7 13 11 PM

I'll start from scratch and get back to you. Sorry for the trouble.

**Comment by 678098** [comment]
@sindhunaydu there are 3 commits in the PR, and signature is missing for the 1st one
Have you tried exec `git reset --soft HEAD~3`? It should undo 3 latest commits but save all changes on disc. Then `git commit -s -m "Implement toString() fn in PutMessageAdapter and AckMessageAdapter"` to make just 1 commit with a signature. It should make everything work.

**Comment by sindhunaydu** [comment]
@678098 you are right, fixed it. now there is only one commit with the expected signature.

**Review by 678098 — APPROVED** [review]

**Comment by 678098** [comment]
@sindhunaydu thank you!

**Comment by sindhunaydu** [comment]
@678098 great! thank you for your help.

**Pull request merged**
