### PR TITLE
Set atomic before enqueueing (DIS)CONNECTED event

### PR DESCRIPTION
**Pull request by sgalichkin**
**Describe your changes**
Modify `BrokerSession::startAsync()` and `BrokerSession::stopAsync()` to set atomic before enqueueing (DIS)CONNECTED session event. Otherwise the the following scenario is possible:
1. Call startAsync/stopAsync
2. Get (DIS)CONNECTED event
3. Call startAsync/stopAsync again
4. Get (DIS)CONNECTION_IN_PROGRESS event while (DIS)CONNECTED is expected instead

**Testing performed**
Two simple unit-tests are provided

### CODE REVIEW

**Comment by sgalichkin** [comment]
@678098 found error in unit-test, will fix it and let you know

**Comment by sgalichkin** [comment]
@678098 there are still maybe errors in following methods (not reproduced now):
`BrokerSessionTest.openConfigureQueueRequestFailsTest`
`BrokerSessionTest.closeQueueRequestFailsTest`
To be fixed later.

Question. `spotless:check` is disabled now in CI?

**Comment by 678098** [comment]
@sgalichkin seems so
https://github.com/bloomberg/blazingmq-sdk-java/blob/358eda1e6ea7917e63ee6fb50d15ecd5873dbf56/.github/workflows/build.yaml#L29

**Comment by 678098** [comment]
@sgalichkin is this feature urgent? We might want to merge ITs branch before this branch if there might be errors here.
https://github.com/bloomberg/blazingmq-sdk-java/pull/12

**Comment by sgalichkin** [comment]
> @sgalichkin seems so
> 
> https://github.com/bloomberg/blazingmq-sdk-java/blob/358eda1e6ea7917e63ee6fb50d15ecd5873dbf56/.github/workflows/build.yaml#L29

I suggest to enable it otherwise spotless and code style checks will be useless

**Comment by 678098** [comment]
@sgalichkin 
> I suggest to enable it otherwise spotless and code style checks will be useless
You can do it in your PR then

> It is not urgent and may wait
I am finalizing my PR right now, it will be ready for review by tomorrow

**Comment by 678098** [comment]
@sgalichkin resolved conflicts here, let's wait for CI to merge

**Review by 678098 — APPROVED** [review]

**Pull request merged**
